name: AutoAuto-Curriculum
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.17.0
  - pandas=0.25.0
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - pydotplus=2.0.2
  - opencv=4.1.1
  - pip:
    - tensorflow==1.14.0
